services:
  db:
    image: postgres:16
    container_name: odoo-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:18
    container_name: odoo-web
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8069:8069"
      - "8071:8071" # Longpolling
    env_file: .env
    environment:
      HOST: db
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./custom-addons:/mnt/custom-addons
    command: ["odoo", "--config", "/etc/odoo/odoo.conf"]

  nginx:
    image: nginx:latest
    container_name: odoo-nginx
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
