[options]
addons_path = d:\tcrm\custom_addons,d:\tcrm\custom-addons,d:\tcrm\tcrm-src\tcrm\addons,d:\tcrm\tcrm-src\addons
db_host = localhost
db_name = akod_prod
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = admin
http_port = 8069
list_db = True
server_wide_modules = base,web,tcrm_saas_routing
log_level = warn
dev_mode = all

