from . import propertio_audit_log
from . import propertio_project
from . import propertio_unit
from . import propertio_sale
from . import tcmb_manager
from . import propertio_payment
from . import propertio_payment_cancel_request
from . import crm_lead_inherit
from . import mail_activity
from . import mail_activity_schedule
from . import res_users
from . import propertio_collection_task
from . import propertio_whatsapp_template
from . import res_partner
from . import propertio_offer
from . import propertio_document
from . import propertio_handover
from . import propertio_title_deed
from . import propertio_service_request
from . import propertio_target
from . import propertio_commission
from . import propertio_cash_register
from . import propertio_einvoice
from . import propertio_revenue_period
from . import propertio_notary
from . import propertio_holiday
from . import propertio_report_center
from . import propertio_report_share
from . import account_payment
