# -*- coding: utf-8 -*-
{
    'name': 'TCRM Web Enhance',
    'version': '1.2.3',
    'category': 'Hidden',
    'summary': 'TCRM UI/UX: branding, docs, spacing, toasts, dark mode, responsive polish',
    'depends': [
        'web',
        'website',
        'website_crm',
        'website_hr_recruitment',
        'crm',
        'utm',
        'base_setup',
        'base_import_module',
        'base_install_request',
        'tcrm_propertio',
        'mail',
    ],
    'data': [
        'views/website_branding.xml',
        'views/website_pages.xml',
        'views/contactus_crm.xml',
        'views/docs_templates.xml',
        'views/demo_templates.xml',
        'views/help_links_views.xml',
        'views/res_config_settings_hide_docs.xml',
        'views/res_config_settings_hide_odoo_refs.xml',
        'data/fix_menu_icons.xml',
        'data/hide_apps_gallery.xml',
        'data/hide_crm_org_menus.xml',
        'data/disable_tcrm_com_oauth.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'assets': {
        'web.assets_backend': [
            'tcrm_web_enhance/static/src/scss/tcrm_enhance.scss',
            'tcrm_web_enhance/static/src/xml/hide_documentation_links.xml',
            'tcrm_web_enhance/static/src/xml/hide_enterprise_upsell.xml',
            'tcrm_web_enhance/static/src/xml/hide_chrome_extensions.xml',
            'tcrm_web_enhance/static/src/xml/tcrm_loading_spinner.xml',
            'tcrm_web_enhance/static/src/js/hide_enterprise_upsell.js',
            'tcrm_web_enhance/static/src/js/hide_odoo_user_menu.js',
            'tcrm_web_enhance/static/src/js/home_action_list.js',
            'tcrm_web_enhance/static/src/js/toast_service.js',
            'tcrm_web_enhance/static/src/js/navbar_active.js',
            'tcrm_web_enhance/static/src/js/list_column_drag.js',
        ],
        'web.assets_frontend': [
            'tcrm_web_enhance/static/src/js/dropdown_fix.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
