[options]
addons_path = /mnt/custom-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$2ZvzXgshxNgbA4BwjpFSig$H2kMEhGg0ZbnLca69XMWM.fwPxQ3AIOTZoMLdujkc6zWUeTbt7d6sSJAyGwsLF.OqCPX/DgOmcZc6sIKL24Srg
db_filter = ^%d$
list_db = True
proxy_mode = True
workers = 2
max_cron_threads = 1

