{
    'name': 'TCRM SaaS Core',
    'version': '1.3.1',
    'summary': 'Master module for TCRM Multi-tenancy with Command Center',
    'depends': ['base', 'web', 'tcrm_propertio'],
    'author': 'Tcrm S.A.',
    'license': 'LGPL-3',
    'data': [
        'security/tcrm_saas_groups.xml',
        'security/ir.model.access.csv',
        'security/tcrm_saas_rules.xml',
        'data/tcrm_saas_command_center_assets.xml',
        'views/tenant_views.xml',
        'views/tcrm_saas_ops_views.xml',
        'views/permission_set_views.xml',
        'views/propertio_security_views.xml',
        'views/command_center_views.xml',
        'data/tcrm_saas_catalog_data.xml',
        'data/tcrm_saas_billing_data.xml',
        'data/tcrm_saas_demo_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
            'tcrm_saas_core/static/src/command_center/command_center.scss',
            'tcrm_saas_core/static/src/js/tcrm_command_palette.js',
            'tcrm_saas_core/static/src/command_center/dashboard/sparkline_utils.js',
            'tcrm_saas_core/static/src/command_center/dashboard/stat_card.xml',
            'tcrm_saas_core/static/src/command_center/dashboard/stat_card.js',
            'tcrm_saas_core/static/src/command_center/dashboard/health_gauges.xml',
            'tcrm_saas_core/static/src/command_center/dashboard/health_gauges.js',
            'tcrm_saas_core/static/src/command_center/dashboard/tenant_map.xml',
            'tcrm_saas_core/static/src/command_center/dashboard/tenant_map.js',
            'tcrm_saas_core/static/src/command_center/command_center.js',
            'tcrm_saas_core/static/src/command_center/command_center.xml',
            'tcrm_saas_core/static/src/command_center/command_center_entry.js',
        ],
    },
    'installable': True,
    'application': True,
}
