{
    'name': 'Propertio',
    'version': '1.4.0',
    'category': 'Real Estate',
    'summary': 'The TCRM Real Estate Engine',
    'author': 'Tcrm S.A.',
    'depends': [
        'base', 'web', 'mail', 'crm', 'account', 'calendar', 'project_todo',
        'tcrm_vector_sync',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/propertio_rules.xml',
        'data/propertio_data.xml',
        'data/propertio_project_master_data.xml',
        'data/propertio_menu_rename.xml',
        'data/propertio_cron.xml',
        'reports/contract_template.xml',
        'views/propertio_menus.xml',
        'views/propertio_dashboard_views.xml',
        'views/propertio_project_views.xml',
        'views/propertio_unit_views.xml',
        'views/sale/propertio_sale_search.xml',
        'views/sale/propertio_sale_list.xml',
        'views/wizards/print_wizard.xml',
        'views/sale/propertio_sale_form.xml',
        'views/payment/propertio_payment_views.xml',
        'views/propertio_payment_cancel_views.xml',
        'views/propertio_audit_log_views.xml',
        'views/wizards/sale_wizard.xml',
        'views/wizards/unified_report_wizard.xml',
        'views/wizards/installment_reallocate_wizard.xml',
        'views/propertio_menus_actions.xml',
        'views/propertio_reporting_views.xml',
        'views/propertio_reports_menu.xml',
        'views/propertio_reports_center_views.xml',
        'reports/propertio_reports.xml',
        'views/propertio_export_wizard.xml',
        'views/crm_lead_views_inherit.xml',
        'views/crm_lead_havuzu_views.xml',
        'views/crm_lead_ui_tr.xml',
        'data/crm_home_defaults.xml',
        'views/mail_activity_schedule_views.xml',
        'views/propertio_core_reports_views.xml',
        'views/propertio_collection_views.xml',
        'views/propertio_whatsapp_views.xml',
        'views/res_partner_views.xml',
        'views/propertio_offer_views.xml',
        'views/propertio_aftersales_views.xml',
        'views/propertio_management_views.xml',
    ],
    'external_dependencies': {
        'python': ['xlsxwriter', 'reportlab', 'qrcode'],
    },
    'assets': {
        'web.assets_backend': [
            'tcrm_propertio/static/src/css/propertio_design.css',
            'tcrm_propertio/static/src/services/propertio_period_service.js',
            'tcrm_propertio/static/src/dashboard/propertio_dashboard.js',
            'tcrm_propertio/static/src/dashboard/propertio_dashboard.xml',
            'tcrm_propertio/static/src/reports_center/propertio_reports_center.js',
            'tcrm_propertio/static/src/reports_center/propertio_reports_center.xml',
            'tcrm_propertio/static/src/crm_havuzu/crm_havuzu_list.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
